---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 2.0.0
  - 2.1.0
script: bundle exec rake spec
env:
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.0.0"
matrix:
  allow_failures:
    - env: PUPPET_VERSION="~> 4.0.0"
